name: Test

on:
    pull_request:
    push:
        branches: [ master ]

jobs:
    tests:
        runs-on: 'ubuntu-latest'
        strategy:
            fail-fast: false
            matrix:
                include:
                    - symfony-version: '6.4.*'
                      php-version: '8.1'
                    - symfony-version: '6.4.*'
                      php-version: '8.2'
                    - symfony-version: '6.4.*'
                      php-version: '8.3'
        steps:
            - name: 'Checkout code'
              uses: actions/checkout@v4

            - name: 'Install PHP with extensions'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2
                  extensions: mbstring
                  ini-values: date.timezone=UTC

            - name: 'Configure Symfony version'
              run: composer require --dev --no-update "symfony/symfony:${{ matrix.symfony-version }}"

            - name: 'Install project dependencies'
              run: composer update --prefer-dist --prefer-stable

            - name: 'Run tests'
              run: vendor/bin/phpunit
